### ISSUE TITLE
Error java.lang.NoClassDefFoundError: com.soomla.Foreground in Android 2.3.3, 2.3.4, 2.3.6 

### ISSUE THREAD

**Issue by noblakit01** [soomla/unity3d-profile#8]
My game worked well in other Android SDK but can start game in Android 2.3.3, 2.3.4, 2.3.6.

Error: java.lang.NoClassDefFoundError: com.soomla.Foreground

:Monkey: seed=0 count=1000
:AllowPackage: com.LuxuStudio.SuperBall
:IncludeCategory: android.intent.category.LAUNCHER
:IncludeCategory: android.intent.category.MONKEY
// Selecting main activities from category android.intent.category.LAUNCHER
//   + Using main activity com.unity3d.player.UnityPlayerNativeActivity (from package com.LuxuStudio.SuperBall)
// Selecting main activities from category android.intent.category.MONKEY
// Seeded: 0
// Event percentages:
//   0: 50.0%
//   1: 50.0%
//   2: -0.0%
//   3: -0.0%
//   4: -0.0%
//   5: -0.0%
//   6: -0.0%
//   7: 0.0%
//   8: -0.0%
:Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10000000;component=com.LuxuStudio.SuperBall/com.unity3d.player.UnityPlayerNativeActivity;end
    // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.LuxuStudio.SuperBall/com.unity3d.player.UnityPlayerNativeActivity } in package com.LuxuStudio.SuperBall
Sleeping for 10 milliseconds
:Sending Pointer ACTION_DOWN x=1024.0 y=464.0
// CRASH: com.LuxuStudio.SuperBall (pid 21053)
// Short Msg: java.lang.NoClassDefFoundError
// Long Msg: java.lang.NoClassDefFoundError: com.soomla.Foreground
// Build Label: samsung/SGH-I717/SGH-I717:2.3.6/GINGERBREAD/UCLA1:user/release-keys
// Build Changelist: UCLA1
// Build Time: 1325882315000
// java.lang.NoClassDefFoundError: com.soomla.Foreground
// 	at com.soomla.SoomlaApp.onCreate(SoomlaApp.java:42)
// 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:972)
// 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3280)
// 	at android.app.ActivityThread.access$2200(ActivityThread.java:117)
// 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
// 	at android.os.Handler.dispatchMessage(Handler.java:99)
// 	at android.os.Looper.loop(Looper.java:130)
// 	at android.app.ActivityThread.main(ActivityThread.java:3691)
// 	at java.lang.reflect.Method.invokeNative(Native Method)
// 	at java.lang.reflect.Method.invoke(Method.java:507)
// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
// 	at dalvik.system.NativeStart.main(Native Method)
// 
** Monkey aborted due to error.
Events injected: 2
:Dropped: keys=0 pointers=0 trackballs=0 flips=0
## Network stats: elapsed time=5608ms (0ms mobile, 5608ms wifi, 0ms not connected)
** System appears to have crashed at event 2 of 1000 using seed 0

Thank you

**Comment by sluzky** [comment]
Hey @noblakit01,

You should import the latest [soomla-unity-core](https://github.com/soomla/soomla-unity3d-core) package, v1.0.4.
Here's a [link](http://library.soom.la/fetch/unity3d-core/1.0.4?cf=github).

**Comment by noblakit01** [comment]
Hey, I imported the lastest soomla-unity-core , v1.0.4 from your link.
 So, It worked, 
But with Android SDK like I said, It can't join to screen.
Here is log error : 
Warning Link of class 'Lcom/soomla/Foreground$ForegroundNew;' failed
Error Could not find class 'com.soomla.Foreground$ForegroundNew', referenced from method com.soomla.Foreground.init
Warning	dalvikvm	VFY: unable to resolve new-instance 1413 (Lcom/soomla/Foreground$ForegroundNew;) in Lcom/soomla/Foreground;

**Comment by sluzky** [comment]
@noblakit01 could it be that you are compiling with the Android 2.* SDK but running on a higher level API device? because from what you described it seems that the device is running on ICS (android 4) at the least.

**Comment by noblakit01** [comment]
@sluzky No, I test with https://appthwack.com.
https://appthwack.com/public/f747767f0f8ba08561d31f3e8

I see that all of device have OS: 2.3.x have same error "Could not find class 'com.soomla.Foreground$ForegroundNew', referenced from method com.soomla.Foreground.init"

What should I do ?

**Comment by sluzky** [comment]
@noblakit01 we have to investigate this further, if you are pressed for time you can always go back to v2.0.1, which shouldn't have these problems, since this is a relatively new feature.
I you decide to do that, please also update soomla-unity3d-core to v1.0.2.

@refaelos this is very strange, can you take a look at this? it seems to be wrongfully detecting the API level in core.

**Comment by refaelos** [comment]
Just tried it on a 2.3.3 device and it looks fine. I tested the android-store project.

@noblakit01 can you try to replace the SoomlaAndroidCore.jar with http://library.soom.la/fetch/android-core/1.0.3?cf=direct  ?

**Comment by refaelos** [comment]
Closing this issue... open if still relevant.

**Comment by tmsoft** [comment]
This is still an issue and I'm seeing it on my 2.3.4 android device using cocos2dx c++ soomla store v4.5.5.

**Comment by refaelos** [comment]
@vedi please let's add this to the the public trello board.

**Comment by EugeneButusov** [comment]
@refaelos, ticket in SOOMLA Public Roadmap: https://trello.com/c/0pwLg5uI/111-test-android-core-cannot-find-com-soomla-foreground-class-in-android-v2-3-x
