### ISSUE TITLE
java.lang.NoSuchMethodError: no static method with name='pushEventGetContactsFailed'

### ISSUE THREAD

**Issue by BurntDragon** [soomla/unity3d-profile#95]
Hello all,
Yesterday I got that error on android:
I/Unity   ( 4767): AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='pushEventGetContactsFailed' signature='(Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)V' in class Lcom/soomla/profile/unity/ProfileEventHandler;
I/Unity   ( 4767): java.lang.NoSuchMethodError: no static method with name='pushEventGetContactsFailed' signature='(Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)V' in class Lcom/soomla/profile/unity/ProfileEventHandler;
I/Unity   ( 4767):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity   ( 4767):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity   ( 4767):      at com.unity3d.player.UnityPlayer.a(Unknown Source)
I/Unity   ( 4767):      at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
I/Unity   ( 4767):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
I/Unity   ( 4767):   at UnityEngine.AndroidJNISafe.GetStaticMethodID (IntPtr clazz, System.String name, System.String sig) [0x00000] in <filename unknown>:0
I/Unity   ( 4767):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boo

Please update unity-android-profile/src/com/soomla/profile/unity/ProfileEventHandler.java
line 672:     
public static void pushEventGetContactsFailed(String providerStr, String message, Boolean fromStart, String payload) {

with:
public static void pushEventGetContactsFailed(String providerStr, String message, boolean fromStart, String payload) {

**Comment by Blinkq** [comment]
Hello @BurntDragon , thank you for your solution. We will try to find time to implement it. We also always open for contribution. You can create PR and we will implement it

**Comment by BurntDragon** [comment]
Hello @Blinkq,
I created a branch with aforementioned fix.
Do I need permission to push it?

**Comment by Blinkq** [comment]
@BurntDragon no, you just need to create Pull Request  from your branch to Soomla master branch, and we will merge it.
